Fix more exceptions in getCircuit() caused by malformed responses
E.g.

  2021-03-16 10:29:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.bmr_hc64_corridor_temperature fails
  Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
      await self.async_device_update()
    File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
      raise exc
    File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
      result = self.fn(*self.args, **self.kwargs)
    File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 259, in wrapper
      result = method(*args, **kwargs)
    File "/config/custom_components/bmr/sensor.py", line 110, in update
      circuit = self._bmr.getCircuit(self._config.get(CONF_CIRCUIT_ID))
    File "/usr/local/lib/python3.8/site-packages/cachetools/func.py", line 64, in wrapper
      v = func(*args, **kwargs)
    File "/config/pybmr/__init__.py", line 47, in wrapped
      return func(self, *args, **kwargs)
    File "/config/pybmr/__init__.py", line 209, in getCircuit
      "warning": int(room_status["warning"]),
  ValueError: invalid literal for int() with base 10: '1-1'